name: Continuous Integration Test

on:
  push:
    branches: ["test"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Run server tests
      run: npm run test
      env:
        _PORT: ${{ secrets._PORT }}
        _MONGO_URI: ${{ secrets._MONGO_URI }}
        _SESSION_SECRET: ${{secrets._SESSION_SECRET}}
        _CLOUDINARY_CLOUD_NAME: ${{secrets._CLOUDINARY_CLOUD_NAME}}
        _CLOUDINARY_API_KEY: ${{secrets._CLOUDINARY_API_KEY}}
        _CLOUDINARY_API_SECRET: ${{secrets._CLOUDINARY_API_SECRET}}
        _TOKEN_SECRET: ${{secrets._TOKEN_SECRET}}